<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tip tc n phng thc thanh ton_btn-spinner i_5992ed</name>
   <tag></tag>
   <elementGuidId>cd3d8269-ab0e-4cd7-bd69-a3d4a1d8711e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_next_step']/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.step-footer-continue-btn.btn > i.btn-spinner.icon.icon-button-spinner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>abbb8bf8-05eb-4e6f-beb0-3b0283fd6724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-spinner icon icon-button-spinner</value>
      <webElementGuid>831efae9-31bf-4b18-ae2c-5139aa308d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_next_step&quot;)/button[@class=&quot;step-footer-continue-btn btn&quot;]/i[@class=&quot;btn-spinner icon icon-button-spinner&quot;]</value>
      <webElementGuid>c5bbfd37-dfd2-4ec9-a83a-2cfde11eab16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_next_step']/button/i</value>
      <webElementGuid>959a10cc-3786-46c0-ae28-2d6bfd9bb976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/i</value>
      <webElementGuid>1048abc3-cfff-4dce-adf1-a724bd3cbf57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
