<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__lni lni-close</name>
   <tag></tag>
   <elementGuidId>2de3bc56-3e22-4984-8394-ee0da36ca67d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[8]/div/div[3]/div[2]/div[2]/div/div[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.productSidebarAction > span > i.lni.lni-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>740c6dfc-0359-4e53-9d4c-5b1fe2068ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lni lni-close</value>
      <webElementGuid>a5e1e3a1-a1e4-4477-a9f1-d02f5911a085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-all&quot;)/div[@class=&quot;sidebar-all-wrap&quot;]/div[@class=&quot;sidebar-all-wrap-right active&quot;]/div[@class=&quot;sidebar-all-wrap-right-main&quot;]/div[@class=&quot;sidebar-all-wrap-right-main-list&quot;]/div[@class=&quot;proLoopSidebar&quot;]/div[@class=&quot;productSidebarAction&quot;]/span[1]/i[@class=&quot;lni lni-close&quot;]</value>
      <webElementGuid>9d41dd59-8002-4336-a65b-dab6e7384f08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-all']/div/div[3]/div[2]/div[2]/div/div[5]/span/i</value>
      <webElementGuid>3cf395ee-d84a-4110-beca-c5cf2399884f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/i</value>
      <webElementGuid>2ae48ca3-d6e2-49d0-9c08-6eb9a55ba4c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
