<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sp</name>
   <tag></tag>
   <elementGuidId>00083fbb-9357-4075-a13a-a0fc89cedd0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section[4]/div/div[2]/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7031961f-fda4-475c-9c3a-8547abe6e844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/4904810903871.1_1cc2bc0dd69b4b93895a7d43875c8869_grande.jpg</value>
      <webElementGuid>62be3f05-cfde-4ad3-bb56-8e3336435816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/4904810903871.1_1cc2bc0dd69b4b93895a7d43875c8869_grande.jpg</value>
      <webElementGuid>0678384f-3e9c-403c-add9-d6b934f64020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid lazyloaded</value>
      <webElementGuid>080c9c6c-8ea6-4a94-b9ad-53318ea815aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bộ đồ chơi Tomica Town Gas Station ENEOS</value>
      <webElementGuid>8ccf37e0-def1-477c-be3c-1f73b7421f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-product&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;group-product-main&quot;]/div[@class=&quot;proLoop&quot;]/div[@class=&quot;proWrap&quot;]/div[@class=&quot;productImg&quot;]/a[@class=&quot;productImgLink&quot;]/picture[2]/img[@class=&quot;img-fluid lazyloaded&quot;]</value>
      <webElementGuid>03d95562-4a5b-4caf-9d65-463bb0eed4ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='group-product']/div/div[2]/div[6]/div/div/a/picture[2]/img</value>
      <webElementGuid>00b116d7-9e75-4629-b0ac-9c7777160716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Bộ đồ chơi Tomica Town Gas Station ENEOS'])[2]</value>
      <webElementGuid>9ec6c7f9-bf8f-48c4-9914-59ab0f3270d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/div/div/a/picture[2]/img</value>
      <webElementGuid>d8b001c4-fb84-4a1c-9470-6f7b39dbdda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/200000504579/product/4904810903871.1_1cc2bc0dd69b4b93895a7d43875c8869_grande.jpg' and @alt = 'Bộ đồ chơi Tomica Town Gas Station ENEOS']</value>
      <webElementGuid>620b00f7-71a0-4b23-b598-1f5c27773c00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
