<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_B  chi ng Ray tu ha Plarail Set Series _82db16</name>
   <tag></tag>
   <elementGuidId>497611a3-d7db-461b-a073-fe0367e58ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section[2]/div/div[2]/div/div/div[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>08cc6ec0-fe5a-47dd-baf5-c37c9d8b59b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/e3753a.1_3a3a33a59de54558ad8e0bce4df47397_grande.jpg</value>
      <webElementGuid>6f22c8c9-9e9d-4ee1-bcd8-0eb0e5552efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/e3753a.1_3a3a33a59de54558ad8e0bce4df47397_grande.jpg</value>
      <webElementGuid>d4ae66c0-f98e-4c8f-a52a-26da19460ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid lazyloaded</value>
      <webElementGuid>94aa72ad-1c3e-488a-87c7-7a5abff9e2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bộ Đồ Chơi E3753A Đường Ray Công Trình Đa Tầng HAPE</value>
      <webElementGuid>cec172ed-6b9a-48c4-a991-b33509fd80e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-product-slider&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;group-product-slider-main slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;proLoop slick-slide slick-active&quot;]/div[@class=&quot;proWrap&quot;]/div[@class=&quot;productImg&quot;]/a[@class=&quot;productImgLink&quot;]/picture[2]/img[@class=&quot;img-fluid lazyloaded&quot;]</value>
      <webElementGuid>5b9f5cc0-2cda-417a-8a65-aca585eb009b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='group-product-slider']/div/div[2]/div/div/div[8]/div/div/a/picture[2]/img</value>
      <webElementGuid>23104735-7369-4dd7-b95c-9cb3de7e9355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Bộ Đồ Chơi E3753A Đường Ray Công Trình Đa Tầng HAPE'])[2]</value>
      <webElementGuid>73b2a582-ad96-4bac-89d8-f7a763742406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/a/picture[2]/img</value>
      <webElementGuid>24cccbb6-5057-4f8d-afc7-5cb68036d69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/200000504579/product/e3753a.1_3a3a33a59de54558ad8e0bce4df47397_grande.jpg' and @alt = 'Bộ Đồ Chơi E3753A Đường Ray Công Trình Đa Tầng HAPE']</value>
      <webElementGuid>0a2b546b-576a-41c5-8ae8-56db8a6ed24d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
