<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hotline_lni lni-user</name>
   <tag></tag>
   <elementGuidId>fd33109f-3c3e-4da4-9f6f-bc23f527ed73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.lni.lni-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>59ffad19-c088-44eb-ab52-4b45af57227c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lni lni-user</value>
      <webElementGuid>33e04785-3b6b-423b-8a22-15e0d37d8187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;headerMain&quot;]/div[@class=&quot;headerRight&quot;]/div[@class=&quot;headerUser&quot;]/a[1]/i[@class=&quot;lni lni-user&quot;]</value>
      <webElementGuid>7a807d85-1eef-48fd-9363-fda9113bfebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      <webElementGuid>945963a4-2814-4f46-b40a-8ca6f51aceb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>1b0b0403-37f9-492d-a19f-dc3fe0ae3787</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
