<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hotline_lni lni-user</name>
   <tag></tag>
   <elementGuidId>4ca46eff-2d76-4942-a1c3-54813c3778c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.lni.lni-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dc08d462-5871-41de-b485-b973a2884c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lni lni-user</value>
      <webElementGuid>16c54d76-c664-44d0-a121-d20855e8bada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;headerMain&quot;]/div[@class=&quot;headerRight&quot;]/div[@class=&quot;headerUser&quot;]/a[1]/i[@class=&quot;lni lni-user&quot;]</value>
      <webElementGuid>d8a96ff0-a16d-4945-82f8-1f02da82ac82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      <webElementGuid>f1bd954c-49be-4a6d-a506-33b5615ef24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>ca343cac-bb2b-4a95-becb-2a595562f1b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
