<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hotline_lni lni-user</name>
   <tag></tag>
   <elementGuidId>50a67a43-9c40-4e3d-a8a4-b8836329a288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.lni.lni-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>34cb8f98-5393-4b62-a8bf-ad8fd13e7315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lni lni-user</value>
      <webElementGuid>209685f1-c467-4c56-b845-c216548c86f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;headerMain&quot;]/div[@class=&quot;headerRight&quot;]/div[@class=&quot;headerUser&quot;]/a[1]/i[@class=&quot;lni lni-user&quot;]</value>
      <webElementGuid>dfa8e84b-d860-437f-883b-7e590b38a816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      <webElementGuid>50b04b05-15cd-4329-b7e8-8dc799cb285d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>3380dae6-4378-4e6c-a169-3e14e763e355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
