<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hotline_lni lni-user</name>
   <tag></tag>
   <elementGuidId>09560e4f-a260-4b67-860f-bc2a970072b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.lni.lni-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>55b0fb27-789e-4969-a803-0b79e73b4811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lni lni-user</value>
      <webElementGuid>43d94b4a-a8c2-414e-9f71-491536c32508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;headerMain&quot;]/div[@class=&quot;headerRight&quot;]/div[@class=&quot;headerUser&quot;]/a[1]/i[@class=&quot;lni lni-user&quot;]</value>
      <webElementGuid>45eb1df3-b493-43a6-9f1d-f463abcb2616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[4]/div[2]/a/i</value>
      <webElementGuid>6c6d417a-8d51-4c25-a4e7-ab039cc951f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>0d0b0172-ed63-45b7-9846-a1ed9b1c1816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
