<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_B  chi ng Ray tu ha Plarail Set Series _82db16</name>
   <tag></tag>
   <elementGuidId>b85dd624-b84d-437e-99b9-f70eb33d0fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='group-product-slider']/div/div[2]/div/div/div[8]/div/div/a/picture[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66132f8c-960d-49ba-9ed2-0cd6a3df39f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/e3753a.1_3a3a33a59de54558ad8e0bce4df47397_grande.jpg</value>
      <webElementGuid>2fc1ca11-051d-44a3-95ba-4457e657da7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/e3753a.1_3a3a33a59de54558ad8e0bce4df47397_grande.jpg</value>
      <webElementGuid>372f8f3b-ae4d-4e8c-93d2-cf22b7d18d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid lazyloaded</value>
      <webElementGuid>f5cb006c-2e17-41c5-887c-405bca546816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bộ Đồ Chơi E3753A Đường Ray Công Trình Đa Tầng HAPE</value>
      <webElementGuid>f015ff8e-f7e5-42ea-886c-e83ace20f852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-product-slider&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;group-product-slider-main slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;proLoop slick-slide slick-active&quot;]/div[@class=&quot;proWrap&quot;]/div[@class=&quot;productImg&quot;]/a[@class=&quot;productImgLink&quot;]/picture[2]/img[@class=&quot;img-fluid lazyloaded&quot;]</value>
      <webElementGuid>71a99716-35f8-4707-8f36-25b6cf721a8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='group-product-slider']/div/div[2]/div/div/div[8]/div/div/a/picture[2]/img</value>
      <webElementGuid>08badc64-d853-483c-8206-6b0d2824e8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Bộ Đồ Chơi E3753A Đường Ray Công Trình Đa Tầng HAPE'])[2]</value>
      <webElementGuid>3afe0e67-5fee-483d-89a9-db61568948c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/a/picture[2]/img</value>
      <webElementGuid>3bd45c90-ea78-47ac-b339-63ab9ab99fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/200000504579/product/e3753a.1_3a3a33a59de54558ad8e0bce4df47397_grande.jpg' and @alt = 'Bộ Đồ Chơi E3753A Đường Ray Công Trình Đa Tầng HAPE']</value>
      <webElementGuid>2039ba42-e635-4e5f-9fdb-54657ca64fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
