<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sp</name>
   <tag></tag>
   <elementGuidId>4397f18b-67a6-4956-81bc-d1ee7294758b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section[4]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a33480c-014c-48cc-8032-451ef91eddf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/tomica-ban-do-da-ngoai-picnic-map-3_143dea4d94f443f69a8d93f3e408fc10_grande.jpg</value>
      <webElementGuid>fc7fc203-a4b4-4edf-9198-1eebd220867b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000504579/product/tomica-ban-do-da-ngoai-picnic-map-3_143dea4d94f443f69a8d93f3e408fc10_grande.jpg</value>
      <webElementGuid>91a392f3-c4d3-4a13-891b-393818a26e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid lazyloaded</value>
      <webElementGuid>490604a6-f5f4-4dd0-a6e9-b3b82ac77a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value> Bản đồ khu dã ngoại Tomica Picnic Map </value>
      <webElementGuid>cafca809-0cbc-445f-828a-cffd4c5f1e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-product&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;group-product-main&quot;]/div[@class=&quot;proLoop&quot;]/div[@class=&quot;proWrap&quot;]/div[@class=&quot;productImg&quot;]/a[@class=&quot;productImgLink&quot;]/picture[2]/img[@class=&quot;img-fluid lazyloaded&quot;]</value>
      <webElementGuid>459ce922-9dc7-47e7-9201-b78284c2ec02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='group-product']/div/div[2]/div[2]/div/div/a/picture[2]/img</value>
      <webElementGuid>23033cfb-22d0-48e3-8474-6d2373995a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt=' Bản đồ khu dã ngoại Tomica Picnic Map '])[2]</value>
      <webElementGuid>05d8445d-2f03-4590-8967-a80e26c4dea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a/picture[2]/img</value>
      <webElementGuid>4792afee-b33e-435d-9b8b-10cd7047d4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/200000504579/product/tomica-ban-do-da-ngoai-picnic-map-3_143dea4d94f443f69a8d93f3e408fc10_grande.jpg' and @alt = ' Bản đồ khu dã ngoại Tomica Picnic Map ']</value>
      <webElementGuid>3f310bb3-1bb9-4f53-a7c8-9ca8859b2d29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
