<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TimKiem</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dee275a1-fb77-455b-9987-86270b1ec51e</testSuiteGuid>
   <testCaseLink>
      <guid>640bf053-9d81-4e13-a04a-f3300ae2a057</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TimKiem/TimKiem_TC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2da2d84f-c5e7-4261-98e3-6fda88bd89fc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TimKiem_file/Data_Test_TK</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2da2d84f-c5e7-4261-98e3-6fda88bd89fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input</value>
         <variableId>663161de-f837-4d6c-b68e-c04753780cb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2da2d84f-c5e7-4261-98e3-6fda88bd89fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>result</value>
         <variableId>39de24d2-ccc3-47a7-8293-252074887d29</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
